config/routes.rb
Watcher::Application.routes.draw do

  root :to => "home#index"

  match "/about" => "high_voltage/pages#show", :id => "about"
  match "/press" => "high_voltage/pages#show", :id => "press"

  OmniAuth.config.path_prefix = "/users/auth"
  devise_for :users, controllers: { registrations: 'users/registrations' }, skip: :omniauth_callback
  devise_scope :user do
    namespace :users do
      match 'auth/:provider/callback' => 'authentications#create', as: :omniauth_callback,
            constraints: { provider: Regexp.union(User.omniauth_providers.map(&:to_s)) }
      delete 'auth/:id' => 'authentications#destroy', :as => :authentication
    end
  end

  post "/subscribe" => "splash_subscribers#create"

  resources :reports, only: :index do
    collection do
      get :protocols
    end
  end
  get "/regions" => "reports#regions"

  resources :users, :only => [:show] do
    member do
      get :show_future
    end
  end
  match "/user/:id" => "users#show"

  resources :watcher_reports, :only => [:index]

  namespace :admin do
    resources :base, :only => :index
    resources :sos_messages, :only => [:index, :edit, :update]
    resources :watcher_referrals, :only => :index do
      member do
        post :approve
        post :reject
        post :problem
      end
    end
    resources :user_locations, :only => :index do
      member do
        post :approve
        post :reject
        post :problem
      end
    end

    resources :watcher_report_photos, :only => [:index, :update]
    resources :protocol_photos, :only => [:index, :update] do
      collection do
        get :approved
      end
    end

    resources :user_messages
  end

  namespace :api do
    namespace :v1 do
      resources :authentications, only: :create
      #resources :messages, only: [:create, :update] do
      #  resources :media_items, only: [:create, :update], shallow: true
      #end
      resources :commissions, only: [] do
        collection do
          get :lookup
        end
      end
    end
  end

  namespace :partners_api do
    namespace :v1 do
      resources :profiles, only: [:show, :index]
    end
  end
end

app/models/watcher_referral.rb
# encoding: utf-8

class WatcherReferral < ActiveRecord::Base
  belongs_to :user

  has_many :referral_photos, dependent: :destroy

  STATUSES = ["pending", "approved", "rejected", "problem"]

  validates :user, presence: true
  validates :status, inclusion: { in: STATUSES }

  STATUSES.each do |status|
    class_eval <<-EOF
    scope :#{status}, where(status: :#{status})

    EOF
  end

  #scope :not_done, where("status = 'approved' OR status = 'problem'")
  scope :recent, order(:created_at)
  scope :pending, where(:status => "pending")

  after_initialize :set_default_status
  after_save :update_watcher_status

  attr_accessible :comment

  def status
    ActiveSupport::StringInquirer.new("#{read_attribute(:status)}")
  end

  def approve!(comment = nil)
    self.status = "approved"
    self.comment = comment

    save
  end

  def reject!(comment = nil)
    self.status = "rejected"
    self.comment = comment

    save
  end

  def problem!(comment = nil)
    self.status = "problem"
    self.comment = comment

    save
  end

  private
    def update_watcher_status
      if status != status_was
        self.user.watcher_status = status
        self.user.save!
      end
    end

    def set_default_status
      self.status = "pending" if self.status.blank?
    end
end

app/controllers/admin/watcher_referrals_controller.rb
class Admin::WatcherReferralsController < Admin::BaseController
  load_and_authorize_resource
  before_filter :find_referral, :only => [:approve, :reject, :problem]

  def moderate
    # Not the best way because two moderators can moderate one user at the same time.
    @user = User.pending.first
  end

  def index
    @watcher_referrals = WatcherReferral.order("created_at DESC").pending.page params[:page]
  end

  def approve
    @referral.approve! #params[:watcher_referral][:comment]

    render :js => "$('#watcher_referral_#{@referral.id}_status').html('approve');$('#watcher_referral_#{@referral.id}_actions').remove()"
    #redirect_to admin_watcher_referrals_path
  end

  def reject
    @referral.reject! #params[:watcher_referral][:comment]

    render :js => "$('#watcher_referral_#{@referral.id}_status').html('reject');$('#watcher_referral_#{@referral.id}_actions').remove()"

    #redirect_to admin_watcher_referrals_path
  end
  
  def problem
    @referral.problem! #params[:watcher_referral][:comment]

    render :js => "$('#watcher_referral_#{@referral.id}_status').html('problem');$('#watcher_referral_#{@referral.id}_actions').remove()"

    #redirect_to  admin_watcher_referrals_path
  end

  protected
    def find_referral
      @referral = WatcherReferral.find params[:id]
    end
end

app/views/admin/watcher_referrals/index.html.haml
%h1 Фото направлений

- @watcher_referrals.each do |watcher_referral|
  %p= "##{watcher_referral.id}"
  %p Пользователь:
  - if watcher_referral.user
    %p= "#{watcher_referral.user.email} (#{watcher_referral.user.first_name} #{watcher_referral.user.last_name})"
  -else
    %p Не указан
  %p Комментарий:
  %p= watcher_referral.comment
  %p Статус:
  %div{:id => "watcher_referral_#{watcher_referral.id}_status"}
    = watcher_referral.status
  %p
    - watcher_referral.referral_photos.each do |photo|
      - if photo.image.url
        %p
          = link_to photo.image.url, :target => "__blank" do
            = image_tag photo.image.url, :width => 300
  - if watcher_referral.status == 'pending'
    %div{:id => "watcher_referral_#{watcher_referral.id}_actions"}
      = link_to 'Подтвердить', approve_admin_watcher_referral_path(watcher_referral), :remote => true, :method => :post
      = link_to 'Отклонить', reject_admin_watcher_referral_path(watcher_referral), :remote => true, :method => :post
      = link_to 'Есть проблема', problem_admin_watcher_referral_path(watcher_referral), :remote => true, :method => :post
    -#.approve{:style => 'display:none'}
    -#  = form_for watcher_referral, :url => approve_admin_watcher_referral_path(watcher_referral), :method => :post do |f|
    -#    %p= f.label 'Комментарий'
    -#    %p= f.text_field :comment
    -#    %p= f.submit 'Подтвердить'
    -#.reject{:style => 'display:none'}
    -#  = form_for watcher_referral, :url => reject_admin_watcher_referral_path(watcher_referral), :method => :post do |f|
    -#    %p= f.label 'Комментарий'
    -#    %p= f.text_field :comment
    -#    %p= f.submit 'Отклонить'
    -#.problem{:style => 'display:none'}
    -#  = form_for watcher_referral, :url => problem_admin_watcher_referral_path(watcher_referral), :method => :post do |f|
    -#    %p= f.label 'Комментарий'
    -#    %p= f.text_field :comment
    -#    %p= f.submit 'Есть проблема'

= paginate @watcher_referrals