config/routes.rb
Watcher::Application.routes.draw do

  root :to => "home#index"

  match "/about" => "high_voltage/pages#show", :id => "about"
  match "/press" => "high_voltage/pages#show", :id => "press"

  OmniAuth.config.path_prefix = "/users/auth"
  devise_for :users, controllers: { registrations: 'users/registrations' }, skip: :omniauth_callback
  devise_scope :user do
    namespace :users do
      match 'auth/:provider/callback' => 'authentications#create', as: :omniauth_callback,
            constraints: { provider: Regexp.union(User.omniauth_providers.map(&:to_s)) }
      delete 'auth/:id' => 'authentications#destroy', :as => :authentication
    end
  end

  post "/subscribe" => "splash_subscribers#create"

  resources :reports, only: :index do
    collection do
      get :protocols
    end
  end
  get "/regions" => "reports#regions"

  resources :users, :only => [:show] do
    member do
      get :show_future
    end
  end
  match "/user/:id" => "users#show"

  resources :watcher_reports, :only => [:index]

  namespace :admin do
    resources :base, :only => :index
    resources :sos_messages, :only => [:index, :edit, :update]
    resources :watcher_referrals, :only => :index do
      member do
        post :approve
        post :reject
        post :problem
      end
    end
    resources :user_locations, :only => :index do
      member do
        post :approve
        post :reject
        post :problem
      end
    end

    resources :watcher_report_photos, :only => [:index, :update]
    resources :protocol_photos, :only => [:index, :update] do
      collection do
        get :approved
      end
    end

    resources :user_messages
  end

  namespace :api do
    namespace :v1 do
      resources :authentications, only: :create
      #resources :messages, only: [:create, :update] do
      #  resources :media_items, only: [:create, :update], shallow: true
      #end
      resources :commissions, only: [] do
        collection do
          get :lookup
        end
      end
    end
  end

  namespace :partners_api do
    namespace :v1 do
      resources :profiles, only: [:show, :index]
    end
  end
end

app/models/sos_message.rb
# encoding: utf-8

class SosMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :user_message
  belongs_to :location, :class_name => "UserLocation", foreign_key: :user_location_id
  belongs_to :last_changed_user, :class_name => 'User'

  has_many :photos, class_name: "SosMessagePhoto", dependent: :destroy
  has_many :videos, class_name: "SosMessageVideo", dependent: :destroy

  STATUS = %w(new in_progress done rejected)

  scope :active, where(:status => ["new", "in_progress"])

  before_create :set_status

  def set_status
    self.status = 'new'
  end

end

app/controllers/admin/sos_messages_controller.rb
class Admin::SosMessagesController < Admin::BaseController

  load_and_authorize_resource
  has_scope :active, :type => :boolean

  def index
    @sos_messages = SosMessage.order("id DESC").page params[:page]
  end

  def edit
    @sos_message = SosMessage.find(params[:id])
  end

  def update
    @sos_message = SosMessage.find(params[:id])
    @sos_message.status = params[:sos_message][:status]
    @sos_message.last_changed_user = current_user
    @sos_message.save
    redirect_to admin_sos_messages_path(:active => true)
  end

end

app/controllers/partner/sos_messages_controller.rb
class Partner::SosMessagesController < Partner::BaseController

  def index
    @sos_messages = SosMessage.order("timestamp DESC").page params[:page]
  end

  def edit
    @sos_message = SosMessage.find(params[:id])
  end

  def update
    @sos_message = SosMessage.find(params[:id])
    @sos_message.status = params[:sos_message][:status]
    @sos_message.last_changed_user = current_user
    @sos_message.save
    redirect_to partner_sos_message_path(@sos_message)
  end

end

app/views/admin/sos_messages/edit.html.haml
= form_for(@sos_message, :url => admin_sos_message_path(@sos_message)) do |f|
  %p
    = f.label :status
  %p
    = f.select :status, SosMessage::STATUS
  %p
    = f.submit 'Save'

app/views/admin/sos_messages/index.html.haml
%h1 SOS сообщения
- @sos_messages.each do |sos_message|
  %p= "##{sos_message.user_id}"
  %p= sos_message.created_at
  %p Cообщение:
  %p= sos_message.body
  - if sos_message.location
    %p Номер УИК:
    %p= sos_message.location.commission.number
    %p Регион УИК:
    %p= sos_message.location.commission.region.name
    %p Адрес УИК:
    %p= sos_message.location.commission.try(:address)
  %p Пользователь:
  %p
    - if sos_message.user
      phone #{sos_message.user.phone}
      %br
      name #{sos_message.user.first_name} #{sos_message.user.last_name}
      %br
      email #{sos_message.user.unconfirmed_email}
  %p Статус:
  %p
    = sos_message.status.nil? ? "new" : "#{sos_message.status}"
    - if sos_message.last_changed_user
      изменен #{sos_message.last_changed_user.email}
  %p
    = link_to 'изменить статус', edit_admin_sos_message_path(sos_message)

  %hr/
  %br/

= paginate @sos_messages